import{S as q,a as S,i as u}from"./assets/vendor-c493984e.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&s(c)}).observe(document,{childList:!0,subtree:!0});function e(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(t){if(t.ep)return;t.ep=!0;const o=e(t);fetch(t.href,o)}})();function M(){v.innerHTML="",i()}function g(){w.style.display="inline-block"}function d(){w.style.display="none"}function m(){y.style.display="inline-block"}function i(){y.style.display="none"}function L(a){let r="";a.hits.forEach(e=>{r+=`<div class="gallery-card">
            <a href="${e.largeImageURL}"><img src="${e.webformatURL}" width="360px" alt="${e.tags}"></a>
            <ul class="card-list">
                <li><p>Likes:</p><p>${e.likes}</p></li>
                <li><p>Views:</p><p>${e.views}</p></li>
                <li><p>Comments:</p><p>${e.comments}</p></li>
                <li><p>Downloads:</p><p>${e.downloads}</p></li>
            </ul>
        </div>`}),v.innerHTML+=r,new q(".gallery-card a",{captionsData:"alt",captionDelay:250}).refresh()}async function b(a,r,e){return await S.get("https://pixabay.com/api/",{params:{per_page:e,page:r,key:"44001471-3db462177f0e91bc0a7989cfe",q:a,image_type:"photo",orientation:"horizontal",safesearch:"safe"}})}const v=document.querySelector(".gallery"),R=document.querySelector(".search-bar"),l=document.querySelector(".search-bar input"),w=document.querySelector(".loader"),y=document.querySelector(".leanMore"),p=15;let h=0,n=1,f="";R.addEventListener("submit",async a=>{if(a.preventDefault(),l.value==""||l.value==" ")return;M(),g(),f=l.value,n=1;const r=await b(f,n,p).then(e=>e.data).catch(e=>console.log(e));if(n+=1,r.hits.length==0){u.error({position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"}),d(),a.target.reset();return}L(r),d(),h=Math.ceil(r.totalHits/p),h<n?(u.info({position:"topRight",message:"We're sorry, but you've reached the end of search results."}),i()):m(),a.target.reset()});y.addEventListener("click",async a=>{g(),i();const r=await b(f,n,p).then(s=>s.data).catch(s=>console.log(s));n+=1;const e=document.querySelector(".gallery-card").getBoundingClientRect().height;L(r),window.scrollBy({top:e*2,behavior:"smooth"}),d(),h<n?(u.info({position:"topRight",message:"We're sorry, but you've reached the end of search results."}),i()):m()});
//# sourceMappingURL=commonHelpers.js.map
