import{i as h,S as L,a as b}from"./assets/vendor-c493984e.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))u(e);new MutationObserver(e=>{for(const a of e)if(a.type==="childList")for(const s of a.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&u(s)}).observe(document,{childList:!0,subtree:!0});function r(e){const a={};return e.integrity&&(a.integrity=e.integrity),e.referrerPolicy&&(a.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?a.credentials="include":e.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function u(e){if(e.ep)return;e.ep=!0;const a=r(e);fetch(e.href,a)}})();function p(){l.innerHTML+='<span class="loader"></span>'}function d(){document.querySelector(".loader").remove()}function f(o){l.innerHTML+='<button type="button" class="leanMore">Lean more</button>',document.querySelector(".leanMore").addEventListener("click",o)}function v(){document.querySelector(".leanMore").remove()}function m(o){let t="";o.hits.length==0?h.error({position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"}):o.hits.forEach(r=>{t+=`<div class="gallery-card">
                <a href="${r.largeImageURL}"><img src="${r.webformatURL}" width="360px" alt="${r.tags}"></a>
                <ul class="card-list">
                    <li><p>Likes:</p><p>${r.likes}</p></li>
                    <li><p>Views:</p><p>${r.views}</p></li>
                    <li><p>Comments:</p><p>${r.comments}</p></li>
                    <li><p>Downloads:</p><p>${r.downloads}</p></li>
                </ul>
            </div>`}),l.innerHTML+=t,new L(".gallery-card a",{captionsData:"alt",captionDelay:250}).refresh()}async function y(o,t){return await b.get("https://pixabay.com/api/",{params:{per_page:15,page:t,key:"44001471-3db462177f0e91bc0a7989cfe",q:o,image_type:"photo",orientation:"horizontal",safesearch:"safe"}})}const l=document.querySelector(".gallery"),w=document.querySelector(".search-bar"),i=document.querySelector(".search-bar input");let n=1,c="";w.addEventListener("submit",async o=>{if(o.preventDefault(),console.log("11"),i.value==""||i.value==" ")return;p(),c=i.value,n=1;const t=await y(c,n).then(r=>r.data).catch(r=>console.log(r));n+=1,m(t),d(),f(g),o.target.reset()});async function g(){p(),v();const o=await y(c,n).then(t=>t.data).catch(t=>console.log(t));n+=1,m(o),d(),f(g)}
//# sourceMappingURL=commonHelpers.js.map
